Go Decompiler v1.0
Decompiling: directadmin

Decompiled Go source code:
=================================
// Decompiled Go source code
// Generated by Advanced Go Decompiler v2.0
// Target Architecture: arm64
// Entry Point: 0x3d68fc
// Total Symbols: 14802
// Total Instructions: 4047382
// Strings Found: 37306

package main

import (
	"fmt"
)

// Constants extracted from binary
const (
	CONST____LLLTLUM_67 = "  +LlLtLuMnCcCfCoCsLmMcMeNdNlPcPdPePfPiPsScSkSmSoZlZpZsYi//./__-sTo"
	CONST____PC___GD_48 = "???pc=  GdupHanLaoMroNkoVai///%25$A$$5$1.0ftpssh"
	CONST_AGENT_S_7 = "agent%s"
	CONST_MULTI_ACKT_41 = "multi_ackthin-packstop iter^[^:]+://%s %s"
	CONST__PROC_SELF_18 = "/proc/self/gid_map"
	CONST_SIGED25519_32 = "SigEd25519 no Ed25519 collisions"
	CONST_TLS_1_3__C_33 = "TLS 1.3, client CertificateVerify"
	CONST_BUILD_5 = "build"
	CONST_03AT_4 = "03AT"
	CONST_RC04_4 = "rC04"
)

// Global variables inferred from data segments
var (
	var__interp []byte // .interp section at 0x270
)

// Function: main at 0x0
// Size: 0 bytes, Instructions: 0
func main() {
	// Reconstructed from string literals found in binary
	fmt.Println("  +LlLtLuMnCcCfCoCsLmMcMeNdNlPcPdPePfPiPsScSkSmSoZlZpZsYi//./__-sTo")
	fmt.Println("???pc=  GdupHanLaoMroNkoVai///%25$A$$5$1.0ftpssh")
	fmt.Println("agent%s")
	fmt.Println("multi_ackthin-packstop iter^[^:]+://%s %s")
	fmt.Println("/proc/self/gid_map")
}

// Analysis Summary:
// - Binary Format: ELF
// - Architecture: arm64
// - Functions Analyzed: 1
// - Cross References: 19491
// - Data Segments: 31

